# SQLite version 3.x
development:
  adapter: postgresql
  encoding: UTF8
  database: apps
  pool: 5
  timeout: 5000
  username: momie
  password:
test:
  adapter: postgresql
  encoding: unicode
  pool: 5
  database: dbtiorp8ibp31l
  username: loczufyjiuqmwl
  password: cN5o2gfv5cNppkRt9RkxRNZUzR
  host: ec2-54-204-43-138.compute-1.amazonaws.com
  port: 5432
production:
  adapter: postgresql
  encoding: UTF8
  database: apps
  pool: 5
  timeout: 5000
  username: momie
  password:

  #adapter: postgresql
  #encoding: unicode
  #pool: 5
  #database: dbtiorp8ibp31l
  #username: loczufyjiuqmwl
  #password: cN5o2gfv5cNppkRt9RkxRNZUzR
  #host: ec2-54-204-43-138.compute-1.amazonaws.com
  #port: 5432#